# Introduction to NumPy

## Exercises:

### 1. Update/Upgrade the NumPy package to the latest version

In [ ]:
# Parts 1 and 2 can be executed in Jupyter or the Anacodna Prompt

### 2. Install/Upgrade another package (e.g. Pandas) 

In [1]:
pip install pandas

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 6.3 MB/s eta 0:00:0000:0100:01
  Using cached tzdata-2023.3-py2.py3-none-any.whl (341 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.0/14.0 MB 6.9 MB/s eta 0:00:0000:0100:01
Note: you may need to restart the kernel to use updated packages.


### 3. Import NumPy as <i> np </i>

In [4]:
import numpy as np

### 4. Use the<i> np.array() </i>function to create an array variable - <i>array_hw_1</i> with the numbers 4,5,7 and 10 in it

In [5]:
array_hw_1 = np.array([4,5,7,10])


array([ 4,  5,  7, 10])

### 5. Display the new array on screen

In [ ]:
array_hw_1

### 6. Create a 2x2 array with the same values as <i> array_hw_1 </i> and display it on the screen

In [6]:
new_array = np.array([[4,5], [7,10]])

In [7]:
new_array

array([[ 4,  5],
       [ 7, 10]])

### 7. Call the <i> np.mean() </i> function on each array

In [8]:
np.mean(new_array)

6.5

In [13]:
np.mean(array_hw_1)

6.5

### 8. Use the <i> axis </i> argument to find the mean for all the rows of <i> array_hw_2</i>

In [15]:
np.mean(new_array, axis=1)

array([4.5, 8.5])

### 9. Use the <i>axis</i> argument to find the mean for all the columns of <i>array_hw_2</i>

In [30]:
np.mean(new_array,axis=0)

array([5.5, 7.5])

### 10. Use the <i> Shift + Tab </i> shorcut on <i> np.mean() </i> to check what possible arguments we can specify. 

In [31]:
np.mean()

TypeError: mean() missing 1 required positional argument: 'a'

### 11. Set the <i> dtype </i> argument equal to <i> np.int </i> and compare the results 

In [33]:
np.mean(new_array, axis=1, dtype=int)

array([4, 8])